### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by salvoravida** [salvoravida/dev-api-tunnel#1]
Next steps:
- [ ] (localhostify): support HTTP Bearer Token 3rd domain api scenario
- [ ] (chrome-ext): add popup to show rules
- [ ] (chrome-ext): support editing/saving rules on dev-tools panel
- [ ] (chrome-ext): publish to webStore

Any ideas? Let me know! 🎉
